### ISSUE TITLE
 display.show 的用法

### ISSUE THREAD

**Issue by webduino-cn** [alankrantas/learn-python-on-microbit-guide#1]
尽量还是将display.show用在Images,  https://microbit-micropython.readthedocs.io/en/v2-docs/tutorials/images.html

display.show用来显示数字或是字串, 只是 Images中 Animation的一个特例使用而已! 其实后面也有delay这个参数. 

比较奇怪的是, 反而Animation以及自定义image完全没有介绍.

**Comment by alankrantas** [comment]
感謝。以前倒沒注意。

其實，使用分離的暫停動作，這跟在一般 Python/MicroPython 的習慣更像。我的最終目標是把使用者導到去用 utime/time 而不是 microbit.sleep。microbit 模組太雜了，我覺得過度倚賴它並不是有幫助的。

**Comment by webduino-cn** [comment]
我指的像是 :  display.show("Hello", delay=500)   :)

**Comment by alankrantas** [comment]
@webduino-cn 我知道啊。但就算我知道了，我也不喜歡這樣用。
